// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Standardly
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string StandardlyString = "c176478f-c07f-40da-9b8d-1d4e50ed74e9";
        public static Guid Standardly = new Guid(StandardlyString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int StandardlyMenuGroup = 0x0001;
        public const int StandardlyMenu = 0x0002;
        public const int StandardlyMenuItemGroup = 0x0003;
        public const int StandardlyGenerateCommand = 0x0100;
        public const int StandardlyTemplateFolderCommand = 0x0101;
    }
}