name: Standardly - MSBuild
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build and Restore
        run: msbuild /t:Rebuild /Restore /v:Minimal

      - name: Test
        uses: microsoft/vstest-action@v1.0.0
        with:
            testAssembly: Standardly.Tests.Unit.dll
            searchFolder: .\Standardly.Tests.Unit\bin\Debug\
            runInParallel: true